-- phpMyAdmin SQL Dump
-- version 4.0.10deb1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Apr 28, 2016 at 10:31 PM
-- Server version: 5.5.47-0ubuntu0.14.04.1
-- PHP Version: 5.5.9-1ubuntu4.14

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `aloud.com`
--

-- --------------------------------------------------------

--
-- Table structure for table `articles`
--

CREATE TABLE IF NOT EXISTS `articles` (
  `post_id` int(10) NOT NULL AUTO_INCREMENT,
  `user_id` varchar(30) NOT NULL,
  `post_date` date NOT NULL,
  `post_title` varchar(1000) NOT NULL,
  `article` varchar(5000) NOT NULL,
  PRIMARY KEY (`post_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=12 ;

--
-- Dumping data for table `articles`
--

INSERT INTO `articles` (`post_id`, `user_id`, `post_date`, `post_title`, `article`) VALUES
(1, 'abc', '2016-04-13', 'Gowipe attack strategy', 'Its a clash of clans attack strategy. \r\nWhere troops combination is golem, wizard and pekka. Its so nice and a popular attack stategy.\r\nLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s\r\n											standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a \r\n											type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining \r\n											essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, \r\n											and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\r\n											It is a long established fact that a reader will be distracted by the readable content \r\n											of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution \r\n											of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing\r\n											packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web \r\n											sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose \r\n											(injected humour and the like)'),
(2, 'xxx', '2016-04-08', 'Tour guide at cox bazar', 'Cox bazar is a nice place to give a tour.\r\nIts low living cost there. \r\nWe should go  there once.\r\nLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s\r\n											standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a \r\n											type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining \r\n											essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, \r\n											and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\r\n											It is a long established fact that a reader will be distracted by the readable content \r\n											of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution \r\n											of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing\r\n											packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web \r\n											sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose \r\n											(injected humour and the like)'),
(3, 'xyz', '2016-04-07', '1', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s\r\n											standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a \r\n											type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining \r\n											essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, \r\n											and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\r\n											It is a long established fact that a reader will be distracted by the readable content \r\n											of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution \r\n											of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing\r\n											packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web \r\n											sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose \r\n											(injected humour and the like).'),
(4, 'ijk', '2016-04-03', '2', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s\r\n											standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a \r\n											type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining \r\n											essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, \r\n											and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\r\n											It is a long established fact that a reader will be distracted by the readable content \r\n											of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution \r\n											of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing\r\n											packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web \r\n											sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose \r\n											(injected humour and the like).'),
(5, 'Sigma', '2016-04-15', 'the best way to make a personal blog', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s\r\n											standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a \r\n											type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining \r\n											essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, \r\n											and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\r\n											It is a long established fact that a reader will be distracted by the readable content \r\n											of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution \r\n											of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing\r\n											packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web \r\n											sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose \r\n											(injected humour and the like).'),
(6, 'Phi', '2016-04-04', 'Lorem Ipsum is simply dummy ', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s\r\n											standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a \r\n											type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining \r\n											essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, \r\n											and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\r\n											It is a long established fact that a reader will be distracted by the readable content \r\n											of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution \r\n											of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing\r\n											packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web \r\n											sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose \r\n											(injected humour and the like)'),
(7, 'A', '2016-04-05', 'Illuminati', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s\r\n											standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a \r\n											type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining \r\n											essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, \r\n											and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\r\n											It is a long established fact that a reader will be distracted by the readable content \r\n											of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution \r\n											of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing\r\n											packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web \r\n											sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose \r\n											(injected humour and the like).'),
(8, 'B', '2016-04-27', 'Glock17', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s\r\n											standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a \r\n											type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining \r\n											essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, \r\n											and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\r\n											It is a long established fact that a reader will be distracted by the readable content \r\n											of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution \r\n											of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing\r\n											packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web \r\n											sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose \r\n											(injected humour and the like).'),
(9, 'C', '2016-04-30', 'Ego', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s\r\n											standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a \r\n											type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining \r\n											essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, \r\n											and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\r\n											It is a long established fact that a reader will be distracted by the readable content \r\n											of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution \r\n											of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing\r\n											packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web \r\n											sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose \r\n											(injected humour and the like).'),
(10, 'Zelta', '2016-04-01', 'Sql injection', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s\r\n											standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a \r\n											type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining \r\n											essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, \r\n											and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\r\n											It is a long established fact that a reader will be distracted by the readable content \r\n											of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution \r\n											of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing\r\n											packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web \r\n											sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose \r\n											(injected humour and the like).'),
(11, 'Enter_here', '2016-04-21', 'Why so serious', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s\r\n											standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a \r\n											type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining \r\n											essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, \r\n											and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\r\n											It is a long established fact that a reader will be distracted by the readable content \r\n											of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution \r\n											of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing\r\n											packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web \r\n											sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose \r\n											(injected humour and the like).');

-- --------------------------------------------------------

--
-- Table structure for table `user_details`
--

CREATE TABLE IF NOT EXISTS `user_details` (
  `id` int(5) NOT NULL AUTO_INCREMENT,
  `username` varchar(20) NOT NULL,
  `first_name` varchar(32) NOT NULL,
  `last_name` varchar(32) NOT NULL,
  `email` varchar(64) NOT NULL,
  `password` varchar(20) NOT NULL,
  `access` enum('0','1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=8 ;

--
-- Dumping data for table `user_details`
--

INSERT INTO `user_details` (`id`, `username`, `first_name`, `last_name`, `email`, `password`, `access`) VALUES
(1, 'unreleased', '', '', '', '9ec2658e019628e1fb25', '1'),
(2, 'xxx', '', '', '', '827ccb0eea8a706c4c34', '1'),
(3, 'abc', '', '', '', '123', '1'),
(4, 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', '1'),
(5, 'shakil147258', 'Shakil', 'Ahmed', 'shakil147258@yahoo.com', '123456', '1'),
(6, 'monir.noob', 'Monir', 'Hossain', 'shakil147258@gmail.com', '123456', '0'),
(7, 'Hog_rider', 'hog', 'rider', 'hog_rider@gmail.com', '147258', '0');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
